#ifdef HARDWARE_M5STACK_C
#define HARDWARE_DEFINED
#include "driver/gpio.h"

//#define ENABLE_POWER
//#define POWER_MONITOR_CHARGE_STATE GPIO_NUM_32
//#define POWER_MONITOR_VBATT GPIO_NUM_35
//#define POWER_MONITOR_VBUS GPIO_NUM_36
//#define POWER_MONITOR_DIVISOR 2

#define PIN_INTERRUPT_GENERAL 11

#define ENABLE_I2C
#define I2C_SDA GPIO_NUM_21
#define I2C_SCL GPIO_NUM_22
#define I2C_CLOCK I2C_FREQ_DEFAULT

#define ENABLE_SPI
#define SPI_SCLK GPIO_NUM_13
#define SPI_MOSI GPIO_NUM_21
#define SPI_SS GPIO_NUM_5

#define ENABLE_BM8563
#define PIN_INTERRUPT_BM8563 PIN_INTERRUPT_GENERAL

//#define ENABLE_RTC

#define ENABLE_BLUETOOTH

#define ENABLE_WIFI
#define WIFI_POWER_SAVING WIFI_PS_MAX_MODEM

#define ENABLE_ST7789
#define DISPLAY_WIDTH 160
#define DISPLAY_HEIGHT 80
#define DISPLAY_OFFSET_COLS 40
#define DISPLAY_OFFSET_ROWS 0
#define ST77XX_CS GPIO_NUM_5
#define ST77XX_DC GPIO_NUM_23
#define ST77XX_RST GPIO_NUM_18
#define ST77XX_BL -1

#define ENABLE_CPU_SCALER
#define CPU_FREQ_MHZ_ONDEMAND 240
#define CPU_FREQ_MHZ 80
#define CPU_FREQ_MHZ_NORADIO 10

//#define ENABLE_SERVICE_NTP
//#define ENABLE_SERVICE_OTA

#define ENABLE_SERVICE_SLEEPTUNE
#define SLEEPTUNE_LOOPS_PER_SECOND 3

#define ENABLE_MONOCOLOUR_LED GPIO_NUM_10

#define ENABLE_IR_BLASTER GPIO_NUM_9

#define DEBUG_EVENTS
//#define DEBUG_LOOP_RUNNING
//#define DEBUG_CPU_SCALER_DECISIONS
//#define DEBUG_WIFIMANAGER_ISACTIVE_DECISIONS
#define SDOS_SERIAL_DEBUG_ENABLED true
#define SDOS_SERIAL_DEBUG_UNDERLYING_SYSTEM_DEBUG true


#endif //HARDWARE_M5STACK_C